spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password:
    driverClassName: org.h2.Driver

logging:
  level:
    org:
      springframework:
        data:
          jpa:
            repository: DEBUG
